---
- hosts: webservers
  gather_facts: yes
  vars:
       repository_url: https://github.com/patrikarlos/NSO_A2
  
  tasks:
     - name: Install packages
     
     - name: Clone repository
       git: repo='{{ repository_url }}'
  
      
- hosts: haproxy
  gather_facts: yes
  become: yes
  tasks:
   - name: Haproxy upadating cahe
     apt:
      update_cache: yes
   - name: Installation of haproxy
     become: yes
     apt:
      name: haproxy
      state: present
   - name: Update configuraton file of haproxy
     template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
   - name: HAProxy reinitiation
     service:
       name: haproxy
       state: restarted
