---
- hosts: webservers
  gather_facts: yes
  tasks:
   - name: Updating cache
     become: yes
     apt:
      update_cache: yes
      cache_valid_time: 3600
   - name: Checking whether nginx has been installed
     become: yes
     apt:
      name: nginx
      state: latest
   - name: php-fpm installation
     become: yes
     apt:
      name: php7.4-fpm 
      state: present
   - name: Starting nginx
     become: yes
     service:
         name: nginx
         state: started
   - name: Copying the php file
     become: yes
     copy:
       src: index.php
       dest: /var/www/html/
   - name: template file added
     become: yes
     template:
       src: nginx.conf.j2
       dest: /etc/nginx/sites-available/default
   - name: confuration file enable
     become: yes
     file:
       src: /etc/nginx/sites-available/default
       dest: /etc/nginx/sites-enabled/default
       state: link
   - name: Restarting the Web Servers
     become: yes
     service:
       name: nginx
       state: restarted
- hosts: HAproxy
  gather_facts: yes
  become: yes
  tasks:
   - name: HAproxy updating cache
     apt:
      update_cache: yes
   - name: Installation of HAproxy
     become: yes
     apt:
      name: HAproxy
      state: present
   - name: Update configuraton file of HAproxy
     template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
   - name: HAProxy reinitiation
     service:
       name: HAproxy
       state: restarted
